# Generated by Django 4.0.2 on 2022-03-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.TextField(max_length=100),
        ),
    ]
