# Generated by Django 4.0.2 on 2022-03-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0002_alter_link_link_alter_link_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.CharField(max_length=100),
        ),
    ]
