# Generated by Django 4.0.2 on 2022-03-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0003_alter_link_short_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='short_link',
            new_name='short_url',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='url',
        ),
    ]
