# Generated by Django 4.0.2 on 2022-03-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0004_rename_short_link_link_short_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
