# Generated by Django 4.0.2 on 2022-03-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0005_alter_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='coustom_url',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
