# Generated by Django 4.0.2 on 2022-03-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0006_link_coustom_url_alter_link_short_url_alter_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='coustom_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
