# Generated by Django 4.0.2 on 2022-03-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0008_alter_link_coustom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='coustom_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
